---
- name: Create IDS SYN Attack profiles only
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml

  vars:
    dp_ip:
      - "10.105.192.32"
      - "10.105.192.33"

    ids_syn_defaults:
      rsIDSSYNDestinationAppPortGroup: "http"
      rsIDSSYNAttackActivationThreshold: "2500"
      rsIDSSYNAttackTerminationThreshold: "1500"
      rsIDSSYNAttackPacketReport: "1"

  tasks:
    - block:
        - name: Lock device(s)
          dp_lock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"

        - name: Create IDS SYN Attack profile on each device
          loop: "{{ dp_ip }}"
          loop_control:
            label: "{{ item }} / TEST"
          create_syn_profile:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
            name: "TEST"
            params: "{{ ids_syn_defaults }}"

      always:
        - name: Unlock device(s)
          dp_unlock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"

